### ISSUE TITLE
Can't enable addon

### ISSUE THREAD

**Issue by GitHenryHoover** [passivestar/quickmenu#11]
Hello!

love the idea of this addon, just can't get it to work. I tried installing directly like you suggested in another forum post, but neither that nor the original intended installation method worked.

I've attached my error message, unfortunately I can't make heads or tails of it. 

Thanks in advance!

![blendererror](https://github.com/passivestar/quickmenu/assets/157695099/97fc5074-3ac3-4260-95ef-d4edd3845841)

**Comment by passivestar** [comment]
Hey, that's because old blender versions aren't supported, for quickmenu 3 beta you need at least blender 4.0, and when it releases you'll need blender 4.1

**Comment by GitHenryHoover** [comment]
Ahhhh, I see. Should have considered that, my bad. Thanks for the quick reply!!On Jan 25, 2024, at 2:18 AM, passivestar ***@***.***> wrote:﻿
Hey, that's because old blender versions aren't supported, for quickmenu 3 beta you need at least blender 4.0, and when it releases you'll need blender 4.1
