### ISSUE TITLE
Edges to Rope - turns slider not working properly in 4.3 release version

### ISSUE THREAD

**Issue by AsterJay** [passivestar/quickmenu#19]
When generating ropes in 4.3 with add-on version 3.3.0 there's a single section that responds to the "Turn" slider
The only message i get in "Input" window is: "Input Geometry has unsupported type: Curve"

Having no problems in 4.2, just in 4.3 blender version.

Things I tried:
-Making a new default project
-Enabling/Disabling addon
-Uninstall, then reinstall a fresh downloaded 3.3.0 version
-Deleting manually the addon from folder explorer and reinstalling
-Using an older version (was broken with an older version as well)

![image](https://github.com/user-attachments/assets/3c55f32c-c6d0-4ed2-9ef5-09ac7eb29983)

**Comment by passivestar** [comment]
Thanks for the report

**Comment by AsterJay** [comment]
Works like a charm, thank you!
