### ISSUE TITLE
Error when trying to edit a menu

### ISSUE THREAD

**Issue by Nziner** [passivestar/quickmenu#5]
![image](https://user-images.githubusercontent.com/6568291/164155536-5fd7eb25-f69d-43c3-96f0-f593d0bd258e.png)

**Comment by passivestar** [comment]
You should probably choose an app to open .json files in windows. Notepad would do

<img width="251" alt="Screenshot 2022-04-20 105525" src="https://user-images.githubusercontent.com/60579014/164179231-3cef4862-3012-411f-a606-07f6c9fe68ad.png">

**Comment by Nziner** [comment]
That's weird, I thought I had Notpad++. The association was really lost. It's working, thank you.
